services:
  baricode_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: baricode_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'